/** ข้อความฟอร์ม LIFF — ไทยหลัก · อังกฤษบรรทัดล่างตัวเล็ก */

export const LIFF_COPY = {
  brand: { th: 'โกอ้วน คลังซีฟู้ด', en: 'Ko Ao Seafood' },
  orderTitle: { th: 'สั่งกุ้ง', en: 'Order shrimp' },
  welcome: { th: 'ยินดีต้อนรับ', en: 'Welcome' },
  registerTitle: { th: 'ลงทะเบียนครั้งแรก', en: 'First-time registration' },
  registerHint: {
    th: 'กรอกข้อมูลครั้งเดียว · ครั้งถัดไปสั่งได้ทันที',
    en: 'One-time setup · order faster next time',
  },
  headerHint: {
    th: 'เลือกขนาดและน้ำหนัก · ระบบบันทึกเข้าร้านโดยตรง',
    en: 'Pick size and weight · sent to the shop',
  },
  orderSummary: { th: 'สรุปออเดอร์', en: 'Order summary' },
  deliveryPrefix: { th: 'ส่ง', en: 'Delivery' },
  riverLive: { th: 'กุ้งแม่น้ำเป็น', en: 'Live river shrimp' },
  riverLiveHint: {
    th: 'เลือกได้มากกว่าหนึ่งขนาด · แตะเพื่อกรอกน้ำหนัก',
    en: 'Multiple sizes OK · tap to enter kg',
  },
  deadShrimp: { th: 'กุ้งตาย', en: 'Dead shrimp' },
  deadShrimpHint: { th: 'ไม่บังคับ — เปิดเมื่อต้องการสั่ง', en: 'Optional' },
  orderDead: { th: 'สั่งกุ้งตาย', en: 'Add dead shrimp' },
  on: { th: 'เปิด', en: 'On' },
  off: { th: 'ปิด', en: 'Off' },
  weightKg: { th: 'น้ำหนัก (กก.)', en: 'Weight (kg)' },
  weightAria: { th: 'น้ำหนัก', en: 'Weight' },
  numpadAria: { th: 'ปุ่มตัวเลข', en: 'Number pad' },
  useWeight: { th: 'ใช้น้ำหนักนี้', en: 'Use this weight' },
  deliveryDate: { th: 'วันจัดส่ง', en: 'Delivery date' },
  deliveryDateHint: {
    th: 'ค่าเริ่มต้นเป็นวันนี้ (เวลาไทย)',
    en: 'Default is today (Thailand time)',
  },
  today: { th: 'วันนี้', en: 'Today' },
  otherDay: { th: 'วันอื่น', en: 'Other date' },
  privacy: {
    th: 'ข้อมูลใช้เพื่อจัดส่งและติดต่อร้านเท่านั้น',
    en: 'Used for delivery and contact only',
  },
  close: { th: 'ปิด', en: 'Close' },
  submit: { th: 'ยืนยันสั่งกุ้ง', en: 'Confirm order' },
  submitting: { th: 'กำลังส่ง…', en: 'Sending…' },
  profileSection: { th: 'ข้อมูลลูกค้า', en: 'Your details' },
  profileHint: {
    th: 'ใช้ติดต่อและจัดส่ง — ตรวจสอบให้ถูกต้อง',
    en: 'For delivery and contact',
  },
  customerName: { th: 'ชื่อลูกค้า / ชื่อที่เรียก', en: 'Name' },
  phone: { th: 'เบอร์ติดต่อ', en: 'Phone' },
  notes: { th: 'จุดส่ง / หมายเหตุ', en: 'Delivery notes' },
  namePlaceholder: { th: 'เช่น จ๊ะขียด, ปุ้ย', en: 'e.g. shop or contact name' },
  notesPlaceholder: {
    th: 'จุดส่ง สังเกตุ ฯลฯ',
    en: 'Drop-off point, landmarks, etc.',
  },
  noDefaultSize: {
    th: 'ยังไม่ตั้งไซซ์ประจำ — สั่งครั้งแรกแล้วเลือกขนาดในขั้นถัดไป',
    en: 'No default size yet — choose on the next step',
  },
  nextPickShrimp: { th: 'ถัดไป · เลือกกุ้ง', en: 'Next · choose shrimp' },
  previewBanner: { th: 'ตัวอย่างออกแบบ', en: 'Design preview' },
  returningPreview: { th: 'ลูกค้าเดิม', en: 'Returning' },
  newPreview: { th: 'ลูกค้าใหม่', en: 'New customer' },
  pickPreview: { th: 'เลือกรายชื่อ', en: 'Pick customer' },
  pickTitle: { th: 'เลือกชื่อในรายชื่อเรา', en: 'Select your name' },
  pickHint: {
    th: 'ลูกค้าเก่าที่ยังไม่ผูก LINE — เลือกชื่อที่ตรงกับร้านคุณ',
    en: 'Existing customer — pick the name we know',
  },
  pickSearch: { th: 'ค้นหาชื่อหรือโซน', en: 'Search name or zone' },
  pickEmpty: { th: 'ไม่พบชื่อ', en: 'No match' },
  loading: { th: 'กำลังเปิด…', en: 'Loading…' },
  loadError: { th: 'เปิดฟอร์มไม่สำเร็จ', en: 'Could not open form' },
  submitSuccess: { th: 'ส่งออเดอร์แล้ว', en: 'Order sent' },
  submitFail: { th: 'ส่งไม่สำเร็จ', en: 'Send failed' },
  chatOthersHint: {
    th: 'คนอื่นในร้านสั่งได้โดยพิมพ์ในแชท เช่น จ๊ะขียด 2 โล',
    en: 'Others at your shop can still order by chat',
  },
  todayLabel: { th: 'วันนี้', en: 'Today' },
  kg: { th: 'กก.', en: 'kg' },
  sizes: {
    small: { th: 'เล็ก', en: 'Small' },
    medium: { th: 'กลาง', en: 'Medium' },
    large: { th: 'ใหญ่', en: 'Large' },
  },
  products: {
    small: 'กุ้งเล็ก',
    medium: 'กุ้งกลาง',
    large: 'กุ้งใหญ่',
    dead: 'กุ้งตาย',
  },
};
