// auto-generated by deploy-hosting.yml — ห้ามแก้มือ
// ค่านี้ถูกเขียนทับอัตโนมัติก่อน vite build ทุกครั้งที่ deploy
// รูปแบบ: ai-DDMMYY.N  (DDMMYY = วันที่/เดือน/ปีพศ 2 หลัก, N = ครั้งที่ deploy วันนี้)
export const APP_VERSION = 'ai-dev';
